export const tableName = {
  users: 'users',
  channels: 'channels',
  channelsM2Mprofiles: 'channels_on_profiles',
  streaks: 'streaks',
  fullStreaks: 'full_streaks',
  fullStreaksM2Mprofiles: 'full_streaks_on_profiles',
  transactions: 'transactions',
  markets: 'markets',
  marketCategories: 'market_categories',
  marketProducts: 'market_products',
  productReviews: 'product_reviews',
  studentProfiles: 'student_profiles',
  profilesM2MProducts: 'profiles_on_products',
  badges: 'badges',
  profilesM2Mbadges: 'profiles_on_badges',
  levels: 'levels',
  levelsM2MProfiles: 'levels_on_profiles',
  levelsM2MProducts: 'levels_on_products',
  stories: 'stories',
  achievements: 'achievements',
};
